name: Hunted
version: 0.1
main: com.bendude56.hunted.HuntedPlugin
website: github.com/BenCmd/HuntedPlugin
author: ben_dude56
softdepend: [Spout]
commands:
    manhunt:
        usage:
        description: Controls all HuntedPlugin functions
    m:
        usage:
        description: Controls all HuntedPlugin functions
    startgame:
        usage:
        description: Starts the Manhunt game
    stopgame:
        usage:
        description: Stops the Manhunt game
    join:
        usage:
        description: Joins a Manhunt team
    assign:
        usage:
        description: Assigns a player to a team
    quit:
        usage:
        description: Quits the current game and makes you a spectator
    hunter:
        usage:
        description: Joins team hunters
    hunters:
        usage:
        description: Joins team hunters
    prey:
        usage:
        description: Joins team prey
    spectate:
        usage:
        description: Joins the spectator team
    makeall:
        usage:
        description: Moves all players to a team
    makeeveryone:
        usage:
        description: Moves all players to a team
    spawn:
        usage:
        description: Teleports a player to the world/hunter/prey spawn
    setspawn:
        usage:
        description: Sets the world/hunter/prey spawn
    weather:
        usage:
        description: Changes the Manhunt world weather
    kick:
        usage:
        description: Kicks a player from the game
    setting:
        usage:
        description: Lists or changes a setting
    settings:
        usage:
        description: Lists or changes a setting
    list:
        usage:
        description: Lists the Manhunt players
    status:
        usage:
        description: Returns information on the curretn Manhunt game
    help:
        usage:
        description: Lists some command help