name: Manhunt
version: 1.3
main: com.deaboy.manhunt.ManhuntPlugin
website: github.com/Deaboy/HuntedPlugin
author: Deaboy
soft-depend: [Amber, WorldEdit]
commands:
    manhunt:
        usage:
        description: Access to simple manhunt functions, like help and info.
        aliases: [m, mh]
    mstartgame:
        usage: /mstartgame [lobby]
        description: Starts a manhunt game in the current lobby, or the specified lobby.
        aliases: [startgame]
    mstopgame:
        usage: /mstopgame [lobby]
        description: Stops a manhunt game in the current lobby, or the specified lobby.
        aliases: [stopgame]
    