name: Manhunt
version: 1.3
main: com.bendude56.hunted.ManhuntPlugin
website: github.com/BenCmd/HuntedPlugin
author: Deaboy
soft-depend: [Amber]
commands:
    manhunt:
        usage:
        description: Controls all HuntedPlugin functions
    m:
        usage:
        description: Controls all HuntedPlugin functions
