name: Hunted
version: 0.9
main: com.bendude56.hunted.HuntedPlugin
website: github.com/BenCmd/HuntedPlugin
author: Deaboy
softdepend: [Spout]
commands:
    manhunt:
        usage:
        description: Controls all HuntedPlugin functions
    m:
        usage:
        description: Controls all HuntedPlugin functions