name: Manhunt
version: 1.1
main: com.bendude56.hunted.HuntedPlugin
website: github.com/BenCmd/HuntedPlugin
author: Deaboy
commands:
    manhunt:
        usage:
        description: Controls all HuntedPlugin functions
    m:
        usage:
        description: Controls all HuntedPlugin functions