name: Manhunt
version: 1.3
main: com.deaboy.manhunt.ManhuntPlugin
website: github.com/Deaboy/HuntedPlugin
author: Deaboy
soft-depend: [Amber, WorldEdit]
commands:
    
    ############ General Commands ############
    manhunt:
        usage: /manhunt [help | info]
        description: Access to simple manhunt functions, like help and info.
        aliases: [m, mh]
    mspawn:
        usage: /mspawn [player] [world]
        description: Teleports you to a world's spawn point. If no world is specified, uses the current world.
        aliases: [spawn]
    msetspawn:
        usage: /msetspawn
        description: Changes the current world's spawn point to your location.
        aliases: [setspawn]
    mworld:
        usage: /mworld <arg> [param]...
        description: Performs various world commands, such as listing loaded worlds and teleporting to a different world.
        aliases: [world, mhworld]
    manhuntmode:
        usage: /manhuntmode <mode> [player]
        description: Changes a player's Manhunt mode. Currently available modes - PLAY, EDIT.
        aliases: [mhmode]
    
    ############ Lobbies ############
    mlobby:
        usage: /mlobby <arg> [param]...
        description: Performs various lobby commands, including editing, renaming, creating, and closing.
        aliases: [lobby, mhlobby]
    mjoin:
        usage: /mjoin <lobby> [player]
        description: Joins a Manhunt lobby by it's name. Add a player's name to make them join the lobby.
        aliases: [join , mhjoin]
    mleave:
        usage: /mleave [player]
        description: Leaves the current Manhunt lobby and joins the default lobby. Include a player's name to make them leave.
        aliases: [leave, mhleave]
    mteam:
        usage: /mteam <command> [arg1] [arg2]...
        description: Performs various team commands, like joining  team and clearing a team.
        aliases: [team]
    
    ############ Maps ############
    mmap:
        usage: /mmap <arg> [param]...
        description: Performs various map commands, such as listing available maps, selecting maps, deleting, creating, etc.
        aliases: [map, mhmap]
    mzone:
        usage: /mzone <arg> [param]...
        description: 
        aliases: [zone, mhzone]
    mpoint:
        usage: /mpoint <arg> [param]...
        description:
        aliases: [point, mhpoint]
    
    ############ Game Commands ############
    mstartgame:
        usage: /mstartgame [lobby]
        description: Starts a manhunt game in the current lobby, or the specified lobby.
        aliases: [startgame]
    mstopgame:
        usage: /mstopgame [lobby]
        description: Stops a manhunt game in the current lobby, or the specified lobby.
        aliases: [stopgame]
    
    mverify:
        usage: /mverify
        description: Verifies a Manhunt command.
        aliases: [verify, myes, yes, ok]
    mcancel:
        usage: /mcancel
        description: Cancels a Manhunt command.
        aliases: [cancel, mno, no]
    
    msettings:
        usage: /msettings <arg> [param]...
        description:
        aliases: [settings, mhsettings, msetting, setting, mhsetting, mset, set, mhset]
    
    
    